/** Compatibility shim — schema lives in videoPromptDirector. */
export {
  h3CreativeIrSchema,
  h3ModeSchema,
  h3ModeUiLabel,
  H3_MODE_UI_LABELS,
  h3ModelSchema,
  H3_CANONICAL_MODEL,
  h3QualitySchema,
  h3AspectSchema,
  H3_MODEL_ASPECTS,
  h3AssetTypeSchema,
  h3AssetRoleSchema,
  h3CameraTypeSchema,
  parseH3CreativeIr,
  safeParseH3CreativeIr,
  videoCreativeIrSchema,
  videoModelIdSchema,
  parseVideoCreativeIr,
  safeParseVideoCreativeIr,
  type H3CreativeIr,
  type VideoCreativeIr,
  type H3Mode,
  type H3Model,
  type H3Quality,
  type H3Aspect,
  type H3ModelAspect,
  type H3Asset,
  type H3Subject,
  type H3Shot,
  type H3Dialogue,
  type H3Camera
} from "../videoPromptDirector/schema.js";
